# Generated by Django 4.0.4 on 2022-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_strata', models.IntegerField()),
                ('n_patches', models.IntegerField()),
                ('population', models.IntegerField()),
            ],
        ),
    ]
