# Generated by Django 4.0.4 on 2022-06-01 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='n_patches',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='n_strata',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='population',
        ),
        migrations.AddField(
            model_name='simulation',
            name='hash_simulation',
            field=models.TextField(default=0, max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='json_file',
            field=models.TextField(default=django.utils.timezone.now, max_length=16384),
            preserve_default=False,
        ),
    ]
